sudo: false

cache:
  directories:
  - $HOME/.gradle

language: groovy

jdk:
- oraclejdk8

env:
- TERM=dumb

script:
- ./gradlew codenarcMain

after_success:
  - bash <(curl -s https://codecov.io/bash)